package:utils:
  - changed-files:
      - any-glob-to-any-file: "packages/utils/*"

package:skyhelper:
  - changed-files:
      - any-glob-to-any-file: "packages/skyhelper/*"

package:jobs:
  - changed-files:
      - any-glob-to-any-file: "packages/jobs/*"

package:docs:
  - changed-files:
      - any-glob-to-any-file: "packages/docs/*"

package:constants:
  - changed-files:
      - any-glob-to-any-file: "packages/constants/*"
