version: "3.8"

services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: skyhelper
    volumes:
      - /root/mybot-data:/app/data
    environment:
      - TOKEN
      - MONGO_CONNECTION
      - TOPGG_TOKEN
      - DBL_TOKEN
      - AUTH_TOKEN
      - GUILD
      - SUGGESTION
      - READY_LOGS
      - COMMANDS_USED
      - CONTACT_US
      - BUG_REPORTS
      - SENTRY_DSN
      - SENTRY_AUTH_TOKEN
    ports:
      - 5000:5000
