services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: skyhelper-jobs
    restart: unless-stopped
    environment:
      - TOKEN
      - MONGO_CONNECTION
      - NODE_ENV
      - ERROR_WEBHOOK
