name: Crowdin Action

on:
  schedule:
    - cron: "0 * * * *" # Run every hour
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          localization_branch_name: crowdin_translate
          create_pull_request: true
          pull_request_title: "chore: new translations [crowdin]"
          pull_request_base_branch_name: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}

          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
