name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "dashboard/**"
      - "locales/**"
      - "docker-compose.yml"
      - "Dockerfile"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Run Container
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
          NODE_ENV: production
          MONGO_CONNECTION: ${{secrets.MONGO_CONNECTION}}
          AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}
          SENTRY_DSN: ${{secrets.SENTRY_DSN}}
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
          DBL_TOKEN: ${{secrets.DBL_TOKEN}}
          BUG_REPORTS: ${{secrets.BUG_REPORTS}}
          COMMANDS_USED: ${{secrets.COMMANDS_USED}}
          CONTACT_US: ${{secrets.COMMANDS_USED}}
          ERROR_LOGS: ${{secrets.ERROR_LOGS}}
          GUILD: ${{secrets.GUILD}}
          READY_LOGS: ${{secrets.READY_LOGS}}
          SUGGESTION: ${{secrets.SUGGESTION}}
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
          TOPGG_TOKEN: ${{secrets.TOPGG_TOKEN}}

      - name: Cleanup Unused Images
        run: docker image prune -f
